version: "3.8"
services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: api
    ports:
      - "4000:4000"
    volumes:
      - "./backend/:/app"
      - "/app/node_modules"  # Empêche l'écrasement des dépendances

  web:
    build:
      context: ./frontend/projectmanagement
      dockerfile: Dockerfile
    container_name: web
    ports:
      - "5173:5173"
    volumes:
      - "./frontend/projectmanagement/:/src"
      - "/src/node_modules"  # Empêche l'écrasement des dépendances
      - "./frontend/projectmanagement/public:/src/public"
   

  mongo:
    image: mongo
    restart: always
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: projectmanagement
      MONGO_INITDB_ROOT_PASSWORD: project123
    volumes:
      - db-data:/data/db

volumes:
  db-data: {}
